ets_payment_dotpay_callback_urlc:
    path:  /transaction/{id}/urlc
    controller: ETSPaymentDotpayBundle\Controller\CallbackController::urlc
    methods: [GET, POST]
    requirements:
        id: \d+
