language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=3.1.*
  - SYMFONY_VERSION=3.2.*
  - SYMFONY_VERSION=3.3.*
  - SYMFONY_VERSION=3.4.*

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer install
