language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=3.1.*
  - SYMFONY_VERSION=3.2.*
  - SYMFONY_VERSION=3.3.*
  - SYMFONY_VERSION=3.4.*


before_install:
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit
